"""Faces.

Two OpenCV models do the work, both ONNX and both small enough to fetch once:

* **YuNet** finds faces — boxes plus five landmarks per face.
* **SFace** turns an aligned face into a 128-dimensional vector where the same
  person's faces land close together and different people's land apart.

This module only *finds* faces. Grouping the vectors — deciding that eleven of
them are one person — happens in the desktop shell, in `src-tauri/src/people.rs`,
next to the database that stores them: a threshold defined in two places is two
thresholds, and the assignment has to be written in the same transaction as the
row it belongs to. A group is a *suggestion of identity*, never an assertion —
nothing here decides who anybody is, and the label only ever comes from the
person using the machine.

The thresholds below are the honest part of what this module does. They are
taken from OpenCV's published evaluation of SFace and YuNet's own defaults: at
these values the models are right far more often than not, and a face too small
or too blurry to judge is dropped rather than guessed at. A wrong answer is
worse than a missing one, because it is indistinguishable from a right one.
"""

from __future__ import annotations

import hashlib
import logging
import re
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from . import models

log = logging.getLogger("afterimage.indexer.faces")

# Below this the detector is guessing. YuNet's own default is 0.9; 0.65 keeps
# profile and group shots that 0.9 throws away.
DETECTION_FLOOR = 0.65

# A face smaller than this many pixels on its short edge carries too little
# detail for a 128-d embedding to mean anything.
MIN_FACE_PIXELS = 56

_DETECTORS: dict[str, object] = {}
_RECOGNISER: list[object] = []

# The crop filename is built from the index row id, which is generated by the
# desktop shell. Anything outside this set is replaced rather than escaped, so a
# hostile-looking id cannot walk out of the crop directory.
_UNSAFE = re.compile(r"[^A-Za-z0-9._-]")


@dataclass
class DetectedFace:
    box: tuple[float, float, float, float]
    score: float
    embedding: list[float]
    crop_path: str | None = None
    quality: float = 0.0

    @property
    def size(self) -> float:
        return min(self.box[2], self.box[3])


def _detector(width: int, height: int):
    """A YuNet detector, resized for this image.

    One detector is kept and told the frame size each time. Caching one per
    image size would be a leak in all but name: a photo library has as many
    distinct sizes as it has photographs.
    """
    import cv2  # local import: the service starts without OpenCV

    if not models.bundle_ready("faces"):
        return None

    if not _DETECTORS:
        path = str(models.path_for(models.YUNET))
        _DETECTORS["yunet"] = cv2.FaceDetectorYN.create(
            path, "", (width, height), DETECTION_FLOOR, 0.3, 500
        )

    detector = _DETECTORS.get("yunet")
    if detector is None:
        return None
    detector.setInputSize((width, height))
    return detector


def _recogniser():
    import cv2

    if _RECOGNISER:
        return _RECOGNISER[0]
    if not models.is_present(models.SFACE):
        return None
    try:
        instance = cv2.FaceRecognizerSF.create(str(models.path_for(models.SFACE)), "")
        _RECOGNISER.append(instance)
        return instance
    except Exception as error:  # pragma: no cover
        log.warning("faces: could not load SFace: %s", error)
        return None


def detect(
    path: str,
    faces_dir: str | None = None,
    file_id: str | None = None,
    max_side: int = 1600,
) -> list[DetectedFace]:
    """Every face worth keeping, with its embedding and a crop for the avatar.

    When ``faces_dir`` is given, each face is written there as a small JPEG so
    the renderer can show it: the aligned crop is the only image of that person
    that is small enough to put in a grid of two hundred of them.
    """
    if not models.bundle_ready("faces"):
        return []

    import cv2

    try:
        image = cv2.imread(path, cv2.IMREAD_COLOR)
    except Exception:  # pragma: no cover
        return []
    if image is None:
        return []

    height, width = image.shape[:2]
    # Very large photographs gain nothing from a full-resolution sweep and cost
    # seconds. 1600px keeps a face at the back of a group shot detectable.
    scale = 1.0
    if max(width, height) > max_side:
        scale = max_side / float(max(width, height))
        image = cv2.resize(
            image,
            (max(1, int(width * scale)), max(1, int(height * scale))),
            interpolation=cv2.INTER_AREA,
        )
        height, width = image.shape[:2]

    detector = _detector(width, height)
    if detector is None:
        return []

    try:
        _, raw = detector.detect(image)
    except Exception as error:  # pragma: no cover
        log.debug("faces: detection failed on %s: %s", path, error)
        return []
    if raw is None:
        return []

    recogniser = _recogniser()
    found: list[DetectedFace] = []

    for index, row in enumerate(raw):
        box = (float(row[0]), float(row[1]), float(row[2]), float(row[3]))
        score = float(row[14])
        side = min(box[2], box[3])
        if side < MIN_FACE_PIXELS:
            continue

        embedding: list[float] | None = None
        crop: str | None = None
        if recogniser is not None:
            try:
                aligned = recogniser.alignCrop(image, row)
                feature = recogniser.feature(aligned)
                embedding = [float(value) for value in np.asarray(feature).reshape(-1)]
                crop = _write_crop(aligned, faces_dir, file_id, index, path)
            except Exception as error:  # pragma: no cover
                log.debug("faces: could not embed a face in %s: %s", path, error)

        if embedding is None:
            continue

        # Bigger, more confident and more central wins the cover slot. Centre is
        # measured against the frame so a face at the edge of a group photo does
        # not become somebody's portrait.
        centre_x = (box[0] + box[2] / 2.0) / max(width, 1)
        centre_y = (box[1] + box[3] / 2.0) / max(height, 1)
        centrality = 1.0 - min(1.0, ((centre_x - 0.5) ** 2 + (centre_y - 0.5) ** 2) ** 0.5 * 2.0)
        quality = side * score * (0.6 + 0.4 * centrality)

        found.append(
            DetectedFace(
                box=box,
                score=score,
                embedding=embedding,
                crop_path=crop,
                quality=quality,
            )
        )

    if scale != 1.0:
        # Report boxes in the original image's coordinates; the renderer overlays
        # them on the real file, not on the resized copy used for detection.
        for face in found:
            face.box = (
                face.box[0] / scale,
                face.box[1] / scale,
                face.box[2] / scale,
                face.box[3] / scale,
            )

    return found


def _write_crop(image, faces_dir: str | None, file_id: str | None, index: int, path: str) -> str | None:
    """Save the aligned crop and return its absolute path.

    The aligned output is 112x112; a little larger keeps a person's card sharp
    on a dense display for the price of a few kilobytes.

    When no index row id was sent, the name comes from a digest of the full path
    rather than the file's stem: two folders on one machine can each hold an
    ``IMG_0001.jpg``, and one person's portrait silently overwriting another's is
    not a failure anyone would notice in time to explain it.
    """
    if not faces_dir:
        return None
    import cv2

    try:
        directory = Path(faces_dir).expanduser()
        directory.mkdir(parents=True, exist_ok=True)
        stem = file_id or hashlib.sha1(path.encode("utf-8", "replace")).hexdigest()[:16]
        safe = _UNSAFE.sub("_", stem)
        target = directory / f"{safe}-{index}.jpg"
        enlarged = cv2.resize(image, (160, 160), interpolation=cv2.INTER_CUBIC)
        ok, buffer = cv2.imencode(".jpg", enlarged, [int(cv2.IMWRITE_JPEG_QUALITY), 88])
        if not ok:
            return None
        target.write_bytes(buffer.tobytes())
        return str(target)
    except Exception as error:  # pragma: no cover
        log.debug("faces: could not write a crop for %s: %s", file_id, error)
        return None


def available() -> bool:
    return models.bundle_ready("faces")


def status() -> dict[str, object]:
    return {
        "available": available(),
        "detector": models.is_present(models.YUNET),
        "recogniser": models.is_present(models.SFACE),
        "detectionFloor": DETECTION_FLOOR,
        "minFacePixels": MIN_FACE_PIXELS,
    }
